package com.runvision.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.runvision.bean.SocketRecord;

import com.runvision.bean.SocketRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig socketRecordDaoConfig;

    private final SocketRecordDao socketRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        socketRecordDaoConfig = daoConfigMap.get(SocketRecordDao.class).clone();
        socketRecordDaoConfig.initIdentityScope(type);

        socketRecordDao = new SocketRecordDao(socketRecordDaoConfig, this);

        registerDao(SocketRecord.class, socketRecordDao);
    }
    
    public void clear() {
        socketRecordDaoConfig.clearIdentityScope();
    }

    public SocketRecordDao getSocketRecordDao() {
        return socketRecordDao;
    }

}
